version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: cisa_db
      MYSQL_USER: javier_admin
      MYSQL_PASSWORD: Ciro2014
      MYSQL_ROOT_PASSWORD: Ciro2014
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django_app
    command: >
      sh -c "while ! python -c \"import socket; s = socket.socket(); s.connect(('db', 3306))\" 2>/dev/null; do echo 'Esperando a la base de datos...'; sleep 1; done &&
             python manage.py migrate &&
             python -c \"import os; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings'); import django; django.setup(); from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='rsoloaga').exists() or User.objects.create_superuser('rsoloaga', 'javiersoloaga5@gmail.com', 'Ciro2014**')\" &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: cisa_db
      DB_USER: javier_admin
      DB_PASSWORD: Ciro2014
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db

volumes:
  mysql_data:
