# Generated by Django 5.2.15 on 2026-06-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AddField(
            model_name='news',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del Evento'),
        ),
        migrations.AddField(
            model_name='news',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
