# Generated by Django 5.2.17 on 2026-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_fecha_evento_news_hora_evento_news_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='contacto@cisa.org.ar', max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(default='Av. General Paz 7890, CABA, Argentina', max_length=255, verbose_name='Dirección Central')),
                ('telefono', models.CharField(default='+54 (11) 4567-8901', max_length=50, verbose_name='Teléfono')),
                ('horario_atencion', models.CharField(default='Lunes a Viernes de 9:00 a 18:00 hs.', max_length=150, verbose_name='Horario de Atención')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Instagram Oficial', max_length=50)),
                ('url', models.URLField(verbose_name='Enlace URL')),
                ('icono', models.CharField(choices=[('bi-facebook', 'Facebook'), ('bi-instagram', 'Instagram'), ('bi-twitter-x', 'X (Twitter)'), ('bi-youtube', 'YouTube'), ('bi-whatsapp', 'WhatsApp'), ('bi-globe', 'Sitio Web / Enlace Genérico')], default='bi-globe', help_text='Ícono representativo', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
