# Generated by Django 5.2.17 on 2026-09-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_informacioncontacto_redsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacioncontacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Central'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Horario de Atención'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
