# Generated by Django 5.2.17 on 2026-09-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_informacioncontacto_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioncontacto',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp Oficial (Número con código de país)'),
        ),
    ]
