# Generated by Django 5.2.17 on 2026-09-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_informacioncontacto_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoContactoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(help_text='Nombre visible (Ej: Sede Anexo, Segundo Correo)', max_length=60)),
                ('valor', models.CharField(help_text='Contenido del dato', max_length=255)),
                ('tipo', models.CharField(choices=[('texto', 'Texto / Dirección'), ('correo', 'Correo Electrónico (Enlace mailto)'), ('telefono', 'Teléfono / Móvil (Enlace tel)'), ('enlace', 'Enlace Externo / Web')], default='texto', help_text='Formato del dato', max_length=20)),
                ('icono', models.CharField(default='bi-info-circle', help_text='Clase de Bootstrap Icon', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Dato de Contacto Adicional',
                'verbose_name_plural': 'Datos de Contacto Adicionales',
                'ordering': ['orden', 'etiqueta'],
            },
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp Oficial'),
        ),
        migrations.AlterField(
            model_name='redsocial',
            name='icono',
            field=models.CharField(choices=[('bi-facebook', 'Facebook'), ('bi-instagram', 'Instagram'), ('bi-twitter-x', 'X (Twitter)'), ('bi-youtube', 'YouTube'), ('bi-whatsapp', 'WhatsApp'), ('bi-telegram', 'Telegram'), ('bi-globe', 'Sitio Web / Enlace Genérico')], default='bi-globe', help_text='Ícono representativo', max_length=50),
        ),
    ]
