# Generated by Django 5.2.17 on 2026-09-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_datocontactoadicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datocontactoadicional',
            name='etiqueta',
            field=models.CharField(max_length=60, verbose_name='Nombre del Campo (Ej: Sede Anexo, Teléfono de Guardia)'),
        ),
        migrations.AlterField(
            model_name='datocontactoadicional',
            name='icono',
            field=models.CharField(choices=[('bi-geo-alt-fill', '📍 Dirección / Ubicación'), ('bi-envelope-fill', '✉️ Correo Electrónico'), ('bi-telephone-fill', '📞 Teléfono'), ('bi-clock-fill', '⏰ Horario'), ('bi-globe', '🌐 Sitio Web / Link'), ('bi-info-circle-fill', 'ℹ️ Información General')], default='bi-info-circle-fill', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='datocontactoadicional',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='datocontactoadicional',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto / Dirección'), ('correo', 'Correo Electrónico (Enlace directo)'), ('telefono', 'Teléfono / Móvil'), ('enlace', 'Enlace Web')], default='texto', max_length=20, verbose_name='Tipo de Dato'),
        ),
        migrations.AlterField(
            model_name='datocontactoadicional',
            name='valor',
            field=models.CharField(max_length=255, verbose_name='Dato / Contenido'),
        ),
    ]
