# Generated by Django 5.2.17 on 2026-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_datocontactoadicional_etiqueta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='icono',
            field=models.CharField(choices=[('bi-facebook', 'Facebook'), ('bi-instagram', 'Instagram'), ('bi-twitter-x', 'X (Twitter)'), ('bi-youtube', 'YouTube'), ('bi-globe', 'Sitio Web / Enlace Genérico')], default='bi-globe', help_text='Ícono representativo', max_length=50),
        ),
    ]
