# Generated by Django 5.2.17 on 2026-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_redsocial_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('folletos_cisa', 'Folletos CEDIS / CISA'), ('documentos_iglesia', 'Documentos de la Iglesia')], help_text='Bloque de la página donde aparecerá este documento.', max_length=30, verbose_name='Categoría')),
                ('titulo', models.CharField(help_text="Nombre completo y oficial del documento (ej: 'Constitución Apostólica Provida Mater Ecclesia').", max_length=300, verbose_name='Título oficial')),
                ('subtitulo', models.CharField(blank=True, help_text="Breve descripción complementaria del documento (ej: 'Primer documento pontificio sobre los Institutos Seculares').", max_length=300, verbose_name='Subtítulo / Contexto')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación del documento, su importancia y contexto histórico-doctrinal.', verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, help_text="Año de promulgación, número de canon u otra referencia oficial (ej: '2 de febrero de 1947 · Pío XII').", max_length=200, verbose_name='Referencia canónica / Año')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('enlace', 'Enlace externo'), ('docx', 'DOCX / Word')], default='pdf', help_text='Tipo de recurso que se vinculará (PDF descargable, enlace externo o documento Word).', max_length=10, verbose_name='Formato')),
                ('archivo', models.FileField(blank=True, help_text="Suba aquí el archivo del documento. Solo si no usa 'Enlace externo'.", null=True, upload_to='documentos/', verbose_name='Archivo (PDF / DOCX)')),
                ('url_externa', models.URLField(blank=True, help_text='URL de lectura en línea si no sube un archivo local (ej: https://www.vatican.va/...). Completar uno u otro, no ambos.', verbose_name='Enlace externo (URL)')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número de posición dentro de la categoría (1 = primero).', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmarque para ocultar este documento del sitio sin eliminarlo.', verbose_name='Visible en el sitio')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria', 'orden', 'titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='informacioncontacto',
            options={'verbose_name': '⚙️ Información de Contacto', 'verbose_name_plural': '⚙️ Información de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-fecha'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='correo',
            field=models.EmailField(blank=True, help_text='Dirección de correo institucional principal (ej: contacto@cisa.org.ar).', max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección postal completa de la sede central (ej: Av. General Paz 1234, CABA).', max_length=255, null=True, verbose_name='Dirección Central'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Horarios en los que se puede contactar (ej: Lunes a Viernes de 9:00 a 18:00 hs.).', max_length=150, null=True, verbose_name='Horario de Atención'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono fijo con código de área (ej: +54 (11) 4567-8901).', max_length=50, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='informacioncontacto',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp con código de país y área, sin espacios ni guiones (ej: +5491145678901). Se usará para generar el enlace de chat directo.', max_length=50, null=True, verbose_name='WhatsApp Oficial'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cuerpo',
            field=models.TextField(help_text='Desarrollo completo de la noticia. Puede incluir párrafos, listas, etc.', verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='fecha_evento',
            field=models.DateField(blank=True, help_text='Fecha del evento al que hace referencia la noticia (distinta de la fecha de publicación).', null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='news',
            name='hora_evento',
            field=models.TimeField(blank=True, help_text='Hora de inicio del evento en formato HH:MM.', null=True, verbose_name='Hora del Evento'),
        ),
        migrations.AlterField(
            model_name='news',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal. Formatos: JPG, PNG, WEBP. Tamaño recomendado: 1200×630 px.', null=True, upload_to='noticias/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='news',
            name='resumen',
            field=models.TextField(help_text='Texto corto que aparece en la tarjeta de la noticia (1-2 oraciones).', verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='news',
            name='titulo',
            field=models.CharField(help_text='Título breve de la noticia (máx. 50 caracteres).', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='news',
            name='ubicacion',
            field=models.CharField(blank=True, help_text="Lugar donde se realizará o realizó el evento (ej: 'Sede Central, Salón A').", max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
