# Generated by Django 5.2.16 on 2026-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_documento_alter_informacioncontacto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-fecha'], 'verbose_name': 'Comunicado', 'verbose_name_plural': 'Comunicados'},
        ),
    ]
