# Generated by Django 5.2.15 on 2026-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutos/')),
                ('responsable', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('fundador', models.TextField()),
                ('carisma', models.TextField()),
                ('rama', models.CharField(max_length=50)),
            ],
        ),
    ]
