# Generated by Django 5.2.15 on 2026-07-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='rama',
            field=models.CharField(choices=[('', 'Selecciona una rama...'), ('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Ambas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
