# Generated by Django 5.2.16 on 2026-07-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0002_alter_instituto_email_alter_instituto_rama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='breve_descripcion',
            field=models.TextField(blank=True, help_text='Resumen para la tarjeta en la web', null=True),
        ),
        migrations.AddField(
            model_name='instituto',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='carisma',
            field=models.TextField(verbose_name='Carisma y Espiritualidad'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='fundador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fundador/a'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='rama',
            field=models.CharField(choices=[('', 'Selecciona una rama...'), ('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Ambas'), ('S', 'Sacerdotal'), ('L', 'Laical')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='responsable',
            field=models.CharField(max_length=100, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Teléfono'),
        ),
    ]
