# Generated by Django 5.2.16 on 2026-07-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0003_instituto_breve_descripcion_instituto_sigla_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituto',
            options={'ordering': ['nombre'], 'verbose_name': 'Instituto', 'verbose_name_plural': 'Institutos'},
        ),
        migrations.AddField(
            model_name='instituto',
            name='anio_fundacion',
            field=models.TextField(blank=True, null=True, verbose_name='Año / Fechas de Fundación'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='anio_llegada_argentina',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Año de llegada a Argentina'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='casas_comunidades',
            field=models.TextField(blank=True, null=True, verbose_name='Casas, Comunidades u Obras'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='consejo_gobierno',
            field=models.TextField(blank=True, null=True, verbose_name='Consejo o Equipo de Gobierno'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='foto_fundador',
            field=models.ImageField(blank=True, null=True, upload_to='institutos/fundadores/', verbose_name='Foto del Fundador/a'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='historia',
            field=models.TextField(blank=True, null=True, verbose_name='Historia y Hitos de Fundación'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='numero_miembros',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Miembros (Mundial / Argentina)'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='País de Origen'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='paises_presencia',
            field=models.TextField(blank=True, null=True, verbose_name='Países donde está presente'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='provincias_diocesis',
            field=models.TextField(blank=True, null=True, verbose_name='Provincias o Diócesis en Argentina'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='redes_sociales',
            field=models.TextField(blank=True, null=True, verbose_name='Redes Sociales (Links / Handles)'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='tipo_presencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Presencia (Pastoral, Misión, etc.)'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='breve_descripcion',
            field=models.TextField(blank=True, help_text='Resumen para tarjetas visuales', null=True, verbose_name='Breve Descripción'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='carisma',
            field=models.TextField(blank=True, null=True, verbose_name='Carisma o Espiritualidad'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección / Ubicaciones'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Oficial'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='fundador',
            field=models.TextField(blank=True, null=True, verbose_name='Fundador/a o Proceso Fundacional'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutos/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre Completo del Instituto'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='rama',
            field=models.CharField(choices=[('', 'Selecciona una rama...'), ('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Ambas'), ('S', 'Sacerdotal'), ('L', 'Laical')], default='', max_length=1, verbose_name='Tipo / Rama'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable General'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='sigla',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sigla / Acrónimo'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='telefono',
            field=models.TextField(blank=True, null=True, verbose_name='Teléfonos / Referentes de Contacto'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Sitio Web Oficial'),
        ),
    ]
