# Generated by Django 5.2.16 on 2026-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0004_alter_instituto_options_instituto_anio_fundacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituto',
            name='rama',
        ),
        migrations.AddField(
            model_name='instituto',
            name='tipo_instituto',
            field=models.CharField(choices=[('', 'Selecciona un tipo...'), ('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Ambas'), ('S', 'Sacerdotal'), ('L', 'Laical')], default='', max_length=1, verbose_name='Tipo de Instituto'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='breve_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Breve Descripción'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='numero_miembros',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número de Miembros'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='redes_sociales',
            field=models.TextField(blank=True, null=True, verbose_name='Redes Sociales'),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='tipo_presencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Presencia'),
        ),
    ]
