# Generated by Django 5.2.17 on 2026-09-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_presidente', models.CharField(max_length=150, verbose_name='Nombre del Presidente/a')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico de Contacto')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Institucional')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
            },
        ),
    ]
