# Generated by Django 5.2.17 on 2026-09-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Ej: Presidente/a, Vicepresidente/a, Secretario/a', max_length=100)),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre y Apellido')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización (ej: 1 para Presidente, 2 para Vice, 3 para Secretario)')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='InformacionInstitucional',
        ),
    ]
