# Generated by Django 5.2.17 on 2026-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_autoridad_delete_informacioninstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asamblea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('convocatoria', 'Convocatoria'), ('informe', 'Informe / Acta'), ('comunicado', 'Comunicado')], default='convocatoria', help_text='Seleccione si es una convocatoria previa, un informe posterior o un comunicado general.', max_length=20, verbose_name='Tipo de publicación')),
                ('estado', models.CharField(choices=[('proxima', 'Próxima'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='proxima', help_text="Estado actual de la asamblea: 'Próxima' para futuras, 'Realizada' para ya celebradas.", max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(help_text="Nombre oficial de la asamblea (ej: 'Asamblea Ordinaria CISA 2025 — Primer Semestre').", max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles, temario, resoluciones o resumen de lo tratado en la asamblea.', verbose_name='Descripción / Temario')),
                ('fecha', models.DateField(help_text='Fecha de realización de la asamblea (o fecha estimada si es próxima).', verbose_name='Fecha')),
                ('lugar', models.CharField(blank=True, help_text="Lugar físico o modalidad (ej: 'Sede Central, Buenos Aires' o 'Virtual — Zoom').", max_length=200, verbose_name='Lugar / Modalidad')),
                ('archivo', models.FileField(blank=True, help_text='Suba el acta, convocatoria formal u otro documento en PDF.', null=True, upload_to='asambleas/', verbose_name='Documento adjunto (PDF)')),
                ('url_externa', models.URLField(blank=True, help_text='URL alternativa si el documento está alojado en otro sitio. Use solo si no adjunta archivo.', verbose_name='Enlace externo (URL)')),
                ('destacada', models.BooleanField(default=False, help_text='Marque para resaltar esta asamblea en la parte superior de la página.', verbose_name='Destacada')),
                ('activo', models.BooleanField(default=True, help_text='Desmarque para ocultar esta entrada sin eliminarla.', verbose_name='Visible en el sitio')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número de prioridad cuando dos asambleas tienen la misma fecha (1 = mayor prioridad).', verbose_name='Orden manual')),
            ],
            options={
                'verbose_name': 'Asamblea',
                'verbose_name_plural': 'Asambleas',
                'ordering': ['-fecha', 'orden'],
            },
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(help_text='Ej: Presidente/a, Vicepresidente/a, Secretario/a General.', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='nombre_completo',
            field=models.CharField(help_text='Nombre y apellido completos de la persona que ocupa el cargo.', max_length=150, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Número de posición en la lista (ej: 1 para Presidente, 2 para Vice, 3 para Secretario).', verbose_name='Orden de visualización'),
        ),
    ]
