from django import forms
from .models import Instituto

class InstitutoForm(forms.ModelForm):
    class Meta:
        model = Instituto
        fields = [
            'nombre',
            'sigla',
            'logo',
            'breve_descripcion',
            'historia',
            'carisma',
            'fundador',
            'foto_fundador',
            'anio_fundacion',
            'pais_origen',
            'tipo_instituto',
            'responsable',
            'consejo_gobierno',
            'numero_miembros',
            'paises_presencia',
            'anio_llegada_argentina',
            'provincias_diocesis',
            'casas_comunidades',
            'tipo_presencia',
            'direccion',
            'telefono',
            'email',
            'website',
            'redes_sociales',
        ]
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: Instituto Secular Misioneras de Jesucristo Sacerdote'}),
            'sigla': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: MJS'}),
            'logo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'breve_descripcion': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Resumen de 2 a 3 líneas para tarjetas...'}),
            'historia': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Breve historia, fundación y misión...'}),
            'carisma': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Detalle del carisma o espiritualidad...'}),
            'fundador': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Nombre(s) del fundador/a o proceso fundacional'}),
            'foto_fundador': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'anio_fundacion': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Ej: 1958 o fechas/hitos históricos...'}),
            'pais_origen': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: Argentina'}),
            'tipo_instituto': forms.Select(attrs={'class': 'form-select'}),
            'responsable': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: Norma Graciana Lacrouts (Directora)'}),
            'consejo_gobierno': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Integrantes del consejo o equipo de gobierno...'}),
            'numero_miembros': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: 15 en Argentina / 1400 a nivel mundial'}),
            'paises_presencia': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Listado de países o regiones...'}),
            'anio_llegada_argentina': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: 2002 o no aplica por origen local'}),
            'provincias_diocesis': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Ej: Buenos Aires, Río Negro, San Luis...'}),
            'casas_comunidades': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Nombres de obras, hogares o casas...'}),
            'tipo_presencia': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ej: Pastoral, educativa, social, misión, parroquial'}),
            'direccion': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Direcciones o ubicaciones físicas...'}),
            'telefono': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Teléfonos o celulares de referentes...'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'contacto@instituto.org'}),
            'website': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://www.ejemplo.org'}),
            'redes_sociales': forms.Textarea(attrs={'class': 'form-control', 'rows': 2, 'placeholder': 'Links de Facebook, Instagram, etc...'}),
        }